Updated build dir cleaning scripts

diff --git a/UPPE/build/clean b/UPPE/build/clean
--- a/UPPE/build/clean
+++ b/UPPE/build/clean
@@ -1,11 +1,11 @@
 #! /bin/bash
 
-echo "Cleaning build dirs..."
+echo "Cleaning UPPE build dir ($PWD)..."
+[ -d CMakeFiles ] && echo "-- Found and removing CMakeFiles/" && rm -r CMakeFiles || echo "-- CMakeFiles/ not found"
+[ -e CMake* ] && echo "-- Found and removing CMake*" && rm CMake* || echo "-- CMake* not found"
+[ -e Make* ] && echo "-- Found and removing Make*" && rm Make* || echo "-- Make* not found"
+[ -e cmake* ] && echo "-- Found and removing cmake*" && rm cmake* || echo "-- cmake* not found"
+[ -e Doxyfile.out ] && echo "-- Found and removing Doxyfile.out" && rm Doxyfile.out || echo "-- Doxyfile.out not found"
 
-rm -r CMake* &&
-rm Make* &&
-rm cmake* &&
-rm Doxyfile.out &&
-
-echo "Build dirs cleaned!"
+echo "Build dir cleaned!"
 
diff --git a/build/clean b/build/clean
--- a/build/clean
+++ b/build/clean
@@ -1,27 +1,30 @@
 #! /bin/bash
 
-echo "Cleaning build dirs..."
+CURRENT_PATH=$PWD
+echo "Current path: $CURRENT_PATH"
 
-cd ../XNLO/build &&
-rm -r CMake* &&
-rm Make* &&
-rm cmake* &&
-rm Doxyfile.out &&
-cd ../../build
+cd $CURRENT_PATH/../XNLO/build
+echo "Cleaning XNLO build dir ($PWD)..."
+[ -d CMakeFiles ] && echo "-- Found and removing CMakeFiles/" && rm -r CMakeFiles || echo "-- CMakeFiles/ not found"
+[ -e CMake* ] && echo "-- Found and removing CMake*" && rm CMake* || echo "-- CMake* not found"
+[ -e Make* ] && echo "-- Found and removing Make*" && rm Make* || echo "-- Make* not found"
+[ -e cmake* ] && echo "-- Found and removing cmake*" && rm cmake* || echo "-- cmake* not found"
+[ -e Doxyfile.out ] && echo "-- Found and removing Doxyfile.out" && rm Doxyfile.out || echo "-- Doxyfile.out not found"
 
-cd ../HHGP/build &&
-rm -r CMake* &&
-rm Make* &&
-rm cmake* &&
-rm Doxyfile.out &&
-cd ../../build
+cd $CURRENT_PATH/../HHGP/build
+echo "Cleaning HHGP build dir ($PWD)..."
+[ -d CMakeFiles ] && echo "-- Found and removing CMakeFiles/" && rm -r CMakeFiles || echo "-- CMakeFiles/ not found"
+[ -e CMake* ] && echo "-- Found and removing CMake*" && rm CMake* || echo "-- CMake* not found"
+[ -e Make* ] && echo "-- Found and removing Make*" && rm Make* || echo "-- Make* not found"
+[ -e cmake* ] && echo "-- Found and removing cmake*" && rm cmake* || echo "-- cmake* not found"
+[ -e Doxyfile.out ] && echo "-- Found and removing Doxyfile.out" && rm Doxyfile.out || echo "-- Doxyfile.out not found"
 
-cd ../UPPE/build &&
-rm -r CMake* &&
-rm Make* &&
-rm cmake* &&
-rm Doxyfile.out &&
-cd ../../build
+cd $CURRENT_PATH/../UPPE/build
+echo "Cleaning UPPE build dir ($PWD)..."
+[ -d CMakeFiles ] && echo "-- Found and removing CMakeFiles/" && rm -r CMakeFiles || echo "-- CMakeFiles/ not found"
+[ -e CMake* ] && echo "-- Found and removing CMake*" && rm CMake* || echo "-- CMake* not found"
+[ -e Make* ] && echo "-- Found and removing Make*" && rm Make* || echo "-- Make* not found"
+[ -e cmake* ] && echo "-- Found and removing cmake*" && rm cmake* || echo "-- cmake* not found"
+[ -e Doxyfile.out ] && echo "-- Found and removing Doxyfile.out" && rm Doxyfile.out || echo "-- Doxyfile.out not found"
 
 echo "Build dirs cleaned!"
-
